server:
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: false
  sources:
    youtube: false
    bandcamp: true
    soundcloud: true
    twitch: true
    vimeo: true
    nico: true
    http: false
    local: false
  filters:
    volume: true
    equalizer: true
    karaoke: true
    timescale: true
    tremolo: true
    vibrato: true
    distortion: true
    rotation: true
    channelMix: true
    lowPass: true

lavalink:
  server:
    password: "change-this-password"
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.3"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
    - dependency: "com.dunctebot:skybot-lavalink-plugin:1.7.1"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false

plugins:
  lavasrc:
    sources:
      spotify: true
      applemusic: true
      deezer: true
      yandexmusic: true
      tidal: true
      qobuz: true
      vkmusic: true
      ytdlp: true
      jiosaavn: true
    providers:
      - "ytsearch:%QUERY%"
      - "ytmsearch:%QUERY%"
      - "scsearch:%QUERY%"
      - "dzsearch:%QUERY%"
    lyrics-sources:
      spotify: true
      deezer: true
      youtube: true
      yandexmusic: true
      vkmusic: true
      lrcLib: true

  dunctebot:
    sources:
      getyarn: true
      clypit: true
      reddit: true
      ocremix: true
      tiktok: true
      mixcloud: true
      soundgasm: true
      pixeldrain: true
      tumblr: false

  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true

pluginsDir: "./plugins"
